common/urls.py
'''
파일명 : urls.py
설 명 :  로그인/로그 아웃
생성일 : 2023-02-06
생성자 : user
since 2023.01.09 Copyright (C) by KandJang All right reserved.
'''
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name='common'

urlpatterns = [
   #django.contrib.auth앱의 LoginView 클래스를 활용
   path('login/',auth_views.LoginView.as_view(template_name='common/login.html'),name='login'),

   #logout: LogoutView
   path('logout/',auth_views.LogoutView.as_view(),name='logout'),

   # signup: 회원가입
   path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from pybo.views import base_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/',include('pybo.urls')),
    path('common/',include('common.urls')),
    path('',base_views.index, name='index'),
]

pybo/urls.py
'''
파일명 : urls.py
설 명 : pybo 모든 URL과 view함수의 메핑 담당!
생성일 : 2023-01-25
생성자 : user
since 2023.01.09 Copyright (C) by KandJang All right reserved.
'''


from django.urls import path
from .views import question_views,answer_views,boot_views ,base_views

app_name = 'pybo'

urlpatterns = [
    #bash_view
    path('',base_views.index,name='index'), #view index로 메핑
    path('<int:question_id>/', base_views.detail, name='detail'),

    #answer
    path('answer/create/<int:question_id>/',answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/',answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/',answer_views.answer_delete, name='answer_delete'),
    path('answer/vote/<int:answer_id>/',answer_views.answer_vote, name='answer_vote'),

    #question
    #json
    #path('question/list/json/',question_views.question_list_json, name='question_list_json'),

    path('question/create/',question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/',question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/',question_views.question_delete, name='question_delete'),
    path('question/vote/<int:question_id>/',question_views.question_vote, name='question_vote'),

    #boot
    path('boot/menu/',boot_views.boot_menu, name='boot_menu'),
    path('boot/list/',boot_views.boot_list, name='boot_list'),
    path('boot/reg/',boot_views.boot_reg, name='boot_reg'),
    path('crawling/cgv/',boot_views.crawling_cgv, name='crawling_cgv'),
]

pybo/views/base_views.py
'''
파일명 : base_views.py
설 명 :
생성일 : 2023-02-08
생성자 : user
since 2023.01.09 Copyright (C) by KandJang All right reserved.
'''
import logging
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from ..models import Question
#ctrl+alt+o(alpa) : import 정리
def detail(request, question_id):
    '''question 상세'''
    logging.info('1.question_id:{}'.format(question_id))
    # question=Question.objects.get(id=question_id)
    question = get_object_or_404(Question, pk=question_id)
    logging.info('2.question:{}'.format(question))
    context = {'question': question}
    return render(request, 'pybo/question_detail.html', context)
def index(request):
    '''question 목록'''
    # list order create_date desc
    # logging.info('index 레벨로 출력')
    # 입력인자: http://127.0.0.1:8000/pybo/2
    #view-source:http://127.0.0.1:8000/?kw=%EA%B8%88%EC%9A%94%EC%9D%BC&page=1
    page = request.GET.get('page', '1')  # 페이지
    kw = request.GET.get('kw', '')  # 검색어
    div = request.GET.get('div', '')  # 검색어구분
    size = request.GET.get('size', '10')  # 페이지 사이즈
    logging.info('page:{}'.format(page))
    logging.info('kw:{}'.format(kw))
    logging.info('div:{}'.format(div))
    logging.info('size:{}'.format(size))
    question_list = Question.objects.order_by('-create_date')  # order_by('-필드') desc, asc order_by('필드')
    #subject__contains : 사용 __contains또는 __icontains(대소 문자 구분) :
    if '10' == div:
        logging.info('if 10')
        question_list = question_list.filter(subject__contains=kw)
    elif '20' == div:
        logging.info('elif 20')
        question_list = question_list.filter(content__contains=kw)
    elif '30' == div:
        logging.info('elif 30')
        #포린키 관계 : author'__'username
        # author=models.ForeignKey(User,on_delete=models.CASCADE,related_name='author_question')
        question_list = question_list.filter(author__username__contains=kw)
    # paging
    paginator = Paginator(question_list, size)
    page_obj = paginator.get_page(page)
    # paginator.count : 전체 개시물 개수
    # paginator.per_page : 페이지당 보여줄 게시물 개수
    # paginator.page_range : 페이지범위
    # number: 현재 페이지 번호
    # previous_page_number: 이전 페이지 번호
    # next_page_number: 다음 페이지 번호
    # has_previous : 이전 페이지 유무
    # has_next : 다음 페이지 유무
    # start_index :현재 페이지 시작 인덱스(1부터 시작)
    # end_index: 현재 페이지 끝 인덱스
    # question_list = Question.objects.filter(id=99)  # order_by('-필드') desc, asc order_by('필드')
    context = {'question_list': page_obj,'kw':kw, 'page':page,'div':div,'size':size}
    logging.info('question_list:{}'.format(page_obj))
    return render(request, 'pybo/question_list.html', context)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!--favicon -->
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'favicon.ico' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <!--Bootstrap -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">

    <!--Bootstrap icon-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">

    <script src="{% static 'common.js' %}"></script>
    <title>Pybo</title>
</head>
<body>
  <!--네비게이션바  -->
  {% include 'navbar.html' %}
  <!--네비게이션바  end-->
  <!--기본 템플릿 안에 삽입될 내용  -->
  {% block content %}
  {% endblock %}
  <!--기본 템플릿 안에 삽입될 내용 end  ---------------------------------->
  <script src="{% static 'bootstrap.min.js' %}"></script>

  <!-- javascript start -->
  {% block script %}
  {% endblock %}
  <!-- javascript end -->
</body>
</html>

templates/form_errors.html
<!-- form validation기능 -->
{% if form.errors %}
<div class="alert alert-danger" role="alert">
    {% for field in form %}
        {% if field.errors %}
            <div><strong>{{ field.label }}</strong></div>
            {{ field.errors }}
        {% endif %}
    {% endfor %}
</div>
{% endif %}
<!-- form validation기능 end -->

templates/navbar.html
  <nav class="navbar navbar-expand-lg  border-bottom navbar-dark bg-primary ps-2">
      <a class="navbar-brand" href="{% url 'pybo:index' %}">Pybo</a>
          <button class="navbar-toggler" type="button"
                  data-bs-toggle="collapse" data-bs-target="#navbarNav"
                  aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
          </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <div class="collapse navbar-collapse justify-content-start" >
            <ul class="navbar-nav">
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{% url 'pybo:boot_list' %}">템플릿_리스트</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{% url 'pybo:boot_reg' %}">템플릿_등록</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{% url 'pybo:crawling_cgv' %}">무비차트</a>
                </li>
                <!-- 회원가입 -->
                <li class="nav-item" >
                    {% if not user.is_authenticated %}
                  <a class="nav-link active" aria-current="page"
                     href="{% url 'common:signup' %}">회원가입</a>
                    {% endif %}
                </li>
            </ul>
        </div>
      <div class="collapse navbar-collapse justify-content-end" >
          <ul class="navbar-nav">
            <!--로그인 -->
            <li class="nav-item">
              <!-- 로그인 정보가 있는 경우 -->
              {% if user.is_authenticated %} <!--로그인 상태 라면, is_anonymous: 로그아웃 상태라면 -->
              <a class="nav-link active" aria-current="page"
                 href="{% url 'common:logout' %}">{{ user.username }}
                <i class="bi bi-box-arrow-in-right"></i>
              </a> <!--username:사용자명 -->
              {% else %}
              <a class="nav-link active" aria-current="page"
                 href="{% url 'common:login' %}">로그인
                 <i class="bi bi-box-arrow-left"></i>
              </a>
              {% endif %}
            </li>
            <li class="nav-item">
                <a class="nav-link active" aria-current="page"
                 href="#">
                    <i class="bi bi-twitter"></i>
                </a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page"
                 href="#">
                  <i class="bi bi-instagram"></i>
              </a>
            </li>
          </ul>
      </div>
    </div>
  </nav>